### ISSUE TITLE
Rewrite in Rust.

### ISSUE THREAD

**Issue by portal-chan** [Jellonator/700000items#1]
Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
Featuring: 
zero-cost abstractions 
move semantics 
guaranteed memory safety 
threads without data races 
trait-based generics 
pattern matching 
type inference 
minimal runtime 
efficient C bindings

**Comment by Jellonator** [comment]
Is this a meme or a serious question?

If this is a meme, good meme my friend :ok_hand:

If this is a serious question, sorry for thinking this is a meme. I do like Rust and I briefly considered using it to make this, but I felt like Python was a better option. Mostly because PIL is pretty dank for creating images.
